language: c
compiler: gcc
 
jobs:
    include:
        - os: linux
          dist: xenial
          arch: amd64

        - os: linux
          dist: xenial
          arch: arm64
                    
        - os: linux
          dist: bionic
          arch: amd64

        - os: linux
          dist: bionic
          arch: arm64

        - os: linux
          dist: focal
          arch: amd64

        - os: linux
          dist: focal
          arch: arm64
script:
    - make
    - echo "C\nA\nB\nA\nB\nA\nC\nA\nB\nB\nC\nA\nB\nC\nD\nD\nB\nA\nC\nA" | ./livehist -s ","  
